version: '3.7'

services:
  currency-exchange:
    image: sudhirgaurav1/dockerimage-currency-exchnage-service:0.0.1-SNAPSHOT
    ports:
      - "8000:8000"
    depends_on:
      - naming-server
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
         
  naming-server:
    image: sudhirgaurav1/dockerimage-naming-server:0.0.1-SNAPSHOT
    ports:
      - "8761:8761"